name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller openpyxl pandas

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name "Sistema Lista BraSoft" sistema_lista_brasoft.py

      - name: List dist contents (debug)
        run: |
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sistema_Lista_BraSoft_EXE
          path: dist/*.exe
